//  Created by Monte Hurd on 1/15/14.

#import "Section.h"

@interface Section (Editing)

//TODO: refactor other core data communication (for article etc) into categories.
// (nice to do as catergories as it leaves the core data objects in default state - as they
// existed when generated by xcode)

// Gets the latest revision of wikitext from server for this section.
// The block is passed a string with the wiki text once its retrieved.
- (void)getWikiTextThen:(void (^)(NSString *))block;

- (void)saveWikiText:(NSString *)wikiText then:(void (^)(NSDictionary *))block;

@end
